#!/bin/sh /etc/rc.common
# vim: set ft=sh

# shellcheck disable=SC2034
START=95
STOP=15
EXTRA_COMMANDS=delayed_reload

CONFIG_NAME=vpn-nftset
_DNSMASQ_CONFD=/tmp/dnsmasq.d  # See /tmp/etc/dnsmasq.conf.xxx
mkdir -p "$_DNSMASQ_CONFD"
_CRONTAB_FILE=/etc/crontabs/root
if [ ! -f $_CRONTAB_FILE ]; then
    touch $_CRONTAB_FILE
fi
_ROUTETABLE_FILE=/etc/iproute2/rt_tables
_ROUTETABLE_PREFIX=vpnnftset_
_FWMARK_TABLE=vpnnftset_fw

uci_get() {  # by section type
    ret=$(uci get "${CONFIG_NAME}.@${1}[0].${2}" 2>/dev/null)
    echo "${ret:=$3}"
}

uci_get_bool() {
    case "$(uci_get "$1" "$2")" in
        1|on|true|yes|enabled) return 0;;
    esac
    return 1
}

nftset_add_addresses() {
    nftset_name=$(uci_get "general" "nftset_name")
    for ip in $(uci_get "general" "ip_addresses"); do
        # shellcheck disable=SC1083
        nft add element inet ${_FWMARK_TABLE} "${nftset_name}_v4" { "$ip" } 2>/dev/null || true
        # shellcheck disable=SC1083
        nft add element inet ${_FWMARK_TABLE} "${nftset_name}_v6" { "$ip" } 2>/dev/null || true
    done
}

generate_dnsmasq_conf() {
    outfile=$1

    nftset_name=$(uci_get "general" "nftset_name")
    nftsets="4#inet#${_FWMARK_TABLE}#${nftset_name}_v4,6#inet#${_FWMARK_TABLE}#${nftset_name}_v6"

    dnsservers=""
    for server in $(uci_get "dnsmasq_nftset" "dns_servers"); do
        # server=$(echo "$server" | sed 's/:/#/g')
        if [ -z "$dnsservers" ]; then
            dnsservers="$server"
        else
            dnsservers="$dnsservers,$server"
        fi
    done

    newoutfile="${outfile}.new"
    for domain in $(uci_get "dnsmasq_nftset" "domains"); do
        case "${domain}" in
        */*)
            domain_nameserver=$domain
            domain=$(echo "$domain_nameserver" | awk -F'/' '{print $1}')
            nameserver=$(echo "$domain_nameserver" | awk -F'/' '{print $2}')
            echo "server=/${domain}/${nameserver}" >> "${newoutfile}"
            echo "nftset=/${domain}/${nftsets}" >> "${newoutfile}"
            ;;
        *  )
            if [ -n "$dnsservers" ]; then
                echo "server=/${domain}/${dnsservers}" >> "${newoutfile}"
            fi
            echo "nftset=/${domain}/${nftsets}" >> "${newoutfile}"
            ;;
        esac
    done
    ret=0
    if [ -f "$outfile" ]; then
        md51=$(sort "$outfile" | md5sum | awk '{print $1}')
        md52=$(sort "$newoutfile" | md5sum | awk '{print $1}')
        [ "$md51" != "$md52" ]
        ret=$?
    fi
    mv "$newoutfile" "$outfile"
    return "$ret"
}

cleanup_crontab() {
    sed -i '/vpn-nftset-rulegenerator/d' $_CRONTAB_FILE
}

setup_crontab() {
    nftset_name=$(uci_get "general" "nftset_name")
    nftsetopts="-i 4#inet#${_FWMARK_TABLE}#${nftset_name}_v4 -i 6#inet#${_FWMARK_TABLE}E#${nftset_name}_v6"

    dnsserveropts=""
    for server in $(uci_get "dnsmasq_nftset" "dns_servers"); do
        # server=$(echo "$server" | sed 's/:/#/g')
        if [ -z "$dnsserveropts" ]; then
            dnsserveropts="-s $server"
        else
            dnsserveropts="$dnsserveropts -s $server"
        fi
    done

    gfwlistopts=""
    for gfwlist in $(uci_get "dnsmasq_nftset" "gfwlist_urls"); do
        if [ -z "$gfwlistopts" ]; then
            gfwlistopts="-w $gfwlist"
        else
            gfwlistopts="$gfwlistopts -w $gfwlist"
        fi
    done

    domainlistopts=""
    for domainlist in $(uci_get "dnsmasq_nftset" "domainslist_urls"); do
        if [ -z "$domainlistopts" ]; then
            domainlistopts="-u $domainlist"
        else
            domainlistopts="$domainlistopts -u $domainlist"
        fi
    done

    cleanup_crontab
    cmd="/usr/bin/vpn-nftset-rulegenerator -d $_DNSMASQ_CONFD $gfwlistopts $nftsetopts $dnsserveropts $domainlistopts"
    echo "4 4 * * * $cmd" >> $_CRONTAB_FILE
    $cmd  # run it
}

cleanup_routetable() {
    nftset_name=$(uci_get "general" "nftset_name")
    if [ -n "$nftset_name" ]; then
        nft delete set inet $_FWMARK_TABLE "${nftset_name}_v4" 2>/dev/null
        nft delete set inet $_FWMARK_TABLE "${nftset_name}_v6" 2>/dev/null
    fi
    nft delete table inet $_FWMARK_TABLE 2>/dev/null
    ip rule del fwmark 7 2>/dev/null
    ip -6 rule del fwmark 7 2>/dev/null
    sed -i "/${_ROUTETABLE_PREFIX}/d" $_ROUTETABLE_FILE
}

setup_routetable() {
    nftset_name=$(uci_get "general" "nftset_name")
    if [ -z "$nftset_name" ]; then
        echo "nftset_name not provided, skip.."
        return
    fi
    cleanup_routetable

    nft add table inet $_FWMARK_TABLE
    nft add set inet $_FWMARK_TABLE "${nftset_name}_v4" { type ipv4_addr \; flags interval\; }
    nft add set inet $_FWMARK_TABLE "${nftset_name}_v6"  { type ipv6_addr \; flags interval\; }
    nft add chain inet $_FWMARK_TABLE mangle_prerouting { type filter hook prerouting priority -150 \; policy accept \; }
    nft add chain inet $_FWMARK_TABLE mangle_output { type route hook output priority -150 \; policy accept \; }
    nft add rule inet $_FWMARK_TABLE mangle_prerouting ip daddr "@${nftset_name}_v4" counter meta mark set 0x7
    nft add rule inet $_FWMARK_TABLE mangle_output ip daddr "@${nftset_name}_v4" counter meta mark set 0x7
    nft add rule inet $_FWMARK_TABLE mangle_prerouting ip6 daddr "@${nftset_name}_v6" counter meta mark set 0x7
    nft add rule inet $_FWMARK_TABLE mangle_output ip6 daddr "@${nftset_name}_v6" counter meta mark set 0x7

    interface=$(uci_get "general" "interface")
    if [ -z "$interface" ] || [ "$interface" = "_nil_" ]; then
        return
    fi
    ipaddr=$(ifconfig "$interface" | awk '/inet addr/{print substr($2,6)}')
    ip6addr=$(ifconfig "$interface" | awk '/inet6 addr/{print substr($3,0)}')

    routetable="${_ROUTETABLE_PREFIX}${interface}"
    # ip route flush table "$routetable"
    for num in $(seq 200 250); do  # table num: 0-255
        if ! awk '{print $1}' < $_ROUTETABLE_FILE | grep -q "$num"; then
            echo "$num $routetable" >> $_ROUTETABLE_FILE
            break
        fi
    done
    ip rule add fwmark 7 table "$routetable"
    ip route add default dev "$interface" table "$routetable"

    if [ -n "${ip6addr}" ]; then
        ip -6 rule add fwmark 7 table "$routetable"
        ip -6 route add default dev "$interface" table "$routetable"
    fi
}

restart_dnsmasq() {
    /etc/init.d/dnsmasq restart > /dev/null 2>&1
}

cleanup() {
    cleanup_routetable
    cleanup_crontab
    if ls "$_DNSMASQ_CONFD"/vpn-nftset-*.conf > /dev/null 2>&1; then
        rm -rf "$_DNSMASQ_CONFD"/vpn-nftset-*.conf
        restart_dnsmasq
    fi
}


start() {
    # config_load "$CONFIG_NAME"
    if ! uci_get_bool "general" "enabled"; then
        echo "Not enabled, skip.."
        cleanup
        return
    fi

    if generate_dnsmasq_conf "$_DNSMASQ_CONFD"/vpn-nftset-domains.conf > /dev/null 2>&1; then
        restart_dnsmasq
    fi

    setup_crontab
    setup_routetable
    nftset_add_addresses
}

stop() {
    # config_load "$CONFIG_NAME"
    cleanup
}

reload() {
    start
}

delayed_reload() {
    # FIXME(damnever): dirty fix, see files/luci/model/cbi/vpn-nftset.lua
    (sleep 10 && reload >/dev/null 2>&1) &
}
