#!/bin/sh /etc/rc.common
# vim: set ft=sh

vpniface=$(uci get vpn-nftset.@general[0].interface 2>/dev/null)
if [ "$INTERFACE" != "$vpniface" ]; then
    exit 0
fi

if [ "$ACTION" = "ifdown" ]; then
    /etc/init.d/vpn-nftset stop
else  # ifup
    /etc/init.d/vpn-nftset start
fi
